---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
      - name: clone-repo
        image: alpine/git:1.0.4
        securityContext:
          runAsUser: 1000
        command: ["/bin/sh", "-c", "git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@bitbucket.org/khinkali/jenkins_backup /jenkins_home"]
        volumeMounts:
        - name: jenkins-home
          mountPath: /jenkins_home
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: bitbucket
              key: username
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitbucket
              key: password
      containers:
      - name: jenkins
        image: jenkins:2.60.3
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        ports:
        - containerPort: 8080
        - containerPort: 50000
      volumes:
      - name: jenkins-home
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30180
  - name: jnlp
    protocol: TCP
    port: 50000
    targetPort: 50000
    nodePort: 30500
  type: NodePort
